#/usr/bin/perl
#
# DO NOT ALTER HERE !!!
# THIS IS GENERATED FROM /usr/share/doc/mandrake-release-<RELEASE>/CREDITS
# WHICH IS FILLED FROM THE COOKER WIKI
#
use lib qw(/usr/lib/libDrakX);
use common;
{

	N("Packagers") => "",
	N("Per Oyvind Karlsen") => N("massive packages rebuilding and cleaning, games, sparc port, proofreading of Mandriva tools"),
	N("Guillaume Rousse") => N("cowsay introduction"),
	N("Olivier Thauvin") => N("figlet introduction, Distriblint (checking rpm in the distro)"),
	N("Marcel Pol") => N("xfce4, updated abiword, mono"),
	N("Ben Reser") => N("updated nc with debian patches, fixed some perl packages, dnotify startup script, urpmc, hddtemp, wipe, etc..."),
	N("Thomas Backlund") => N("\"deep and broad\" kernel work (many new patches before integration in official kernel)"),
	N("Svetoslav Slavtchev") => N("kernel work (audio- and video-related patches)"),
	N("Danny Tholen") => N("patches to some packages, kfiresaver, xwine. ppc kernel-benh."),
	N("Buchan Milne") => N("Samba 3.0 (prerelease) that co-exists with Samba 2.2.x, Samba-2.2.x, GIS software (grass, mapserver), cursor_themes collection, misc server-side contributions"),
	N("Goetz Waschk") => N("xine, totem, gstreamer, mplayer, vlc, vcdimager, xmms and plugins gnome-python, rox desktop"),
	N("Austin Acton") => N("audio/video/MIDI apps, scientific apps, audio/video production howtos, bluetooth, pyqt & related"),
	N("Spencer Anderson") => N("ATI/gatos/DRM stuff, opengroupware.org"),
	N("Andrey Borzenkov") => N("supermount-ng and other kernel work"),
	N("Oden Eriksson") => N("most web-based packages and many security-related packages"),
	N("Stefan VanDer Eijk") => N("slbd distro checking, devel dependancies"),
	N("David Walser") => N("rpmsync script, foolproof MIDI playback, tweaked libao"),
	N("Andi Payn") => N("many extra gnome applets and python modules"),
	N("Tibor Pittich") => N("sk-i18n, contributed several packages, openldap testing and integration, bind-sdb-ldap, several years of using cooker and bug hunting, etc..."),
	N("Pascal Terjan") => N("some ruby stuff, php-pear packages, various other stuff."),
	N("Michael Reinsch") => N("moin wiki clone, beep-media-player, im-ja and some other packages"),
	N("Christophe Guilloux") => N("bug reports, help with thunderbird package,..."),
	N("Brook Humphrey") => N("testing and bug reports, Dovecot, bibletime, sword, help with pure-ftpd, spamassassin, maildrop, clamav."),
	N("Olivier Blin") => N("http proxy support in installer, kernel 2.6 support in sndconfig, samba3 support in LinNeighborhood, fixes and enhancements in urpmi, bootsplash and drakxtools"),
	N("Emmanuel Blindauer") => N("lm_sensors for 2.6 kernel, testing, some contrib packages."),
	N("Matthias Debus") => N("sim, pine and some other contrib packages."),
	N("Documentation") => "",
	N("SunnyDubey") => N("wrote/edited parts of gi/docs/HACKING file"),
	N("Translators") => "",
	N("Per Oyvind Karlsen") => N("Norwegian Bokmal (nb) translator and coordinator, i18n work"),
	N("Tibor Pittich") => N("\"one-man\" mdk sk-i18n team"),
	N("Thomas Backlund") => N("Finnish translator and coordinator"),
	N("Reinout Van Schouwen") => N("Dutch translator and coordinator"),
	N("Keld Simonsen") => N("Danish translator (and some Bokmal too:-)"),
	N("Karl Ove Hufthammer") => N("Norwegian Nynorsk (nn) translator and coordinator"),
	N("Marek Laane") => N("Estonian translator"),
	N("Andrea Celli") => N("Italian Translator"),
	N("Simone Riccio") => N("Italian Translator"),
	N("Daniele Pighin") => N("Italian Translator"),
	N("Vedran Ljubovic") => N("Bosnian translator"),
	N("Testers") => "",
	N("Benoit Audouard"), N("testing and bug reporting, integration of eagle-usb driver"),
	N("Bernhard Gruen") => N("testing and bug reporting"),
	N("Jure Repinc") => N("testing and bug reporting"),
	N("Felix Miata") => N("testing and bug reporting"),
	N("Tim Sawchuck") => N("testing and bug reporting"),
	N("Eric Fernandez") => N("testing and bug reporting"),
	N("Ricky Ng-Adam") => N("testing and bug reporting"),
	N("Pierre Jarillon") => N("testing and bug reporting"),
	N("Michael Brower") => N("testing and bug reporting"),
	N("Frederik Himpe") => N("testing and bug reporting"),
	N("Jason Komar") => N("testing and bug reporting"),
	N("Raphael Gertz") => N("testing, bug report, Nvidia package try"),
	N("Simone Riccio") => N("testing, bug reporting"),
	N("Daniele Pighin") => N("testing, bug reporting"),
	N("Fabrice FACORAT") => N("testing, bug reporting"),
	N("Mihai Dobrescu") => N("testing, bug reporting"),
	N("Vedran Ljubovic") => N("testing, bug reporting"),
	N("Mary V. Jones-Giampalo") => N("testing, bug reporting"),
	N("Vincent Meyer") => N("MD, testing, bug reporting"),
	N("And many unnamed and unknown beta testers and bug reporters that helped make sure it all worked right.") => "",
}
