#!/usr/bin/perl
# DrakConsole -- Display Manager chooser
# Copyright (C) 2003 MandrakeSoft (tvignaud@mandrakesoft.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

use strict;
use lib qw(/usr/lib/libDrakX);

use common;
use standalone;     #- warning, standalone must be loaded very first, for 'explanations'
use ugtk3 qw(:create :wrappers);
use Gtk3;
use Glib::Object::Introspection;

Glib::Object::Introspection->setup (
    basename => 'Vte',
    version => '2.91',
    package => 'Gtk3::Vte');

my $w = ugtk3->new(N("DrakConsole"));

$w->{rwindow}->add(gtkpack_(Gtk3::VBox->new(0, 0),
                            1, my $vte = gtksignal_connect(Gtk3::Vte::Terminal->new, 'child-exited' => sub { ugtk3->exit }),
                            0, gtkpack__(create_hbox('end'), gtksignal_connect(Gtk3::Button->new(N("Close")),
                                                                               clicked => sub { ugtk3->exit })
                                         )
                          ),
                  );
$w->{rwindow}->show_all;

$vte->grab_focus();
#$ENV{PS1} = qq(Type "exit"\n);
$vte->spawn_sync('default', undef, [ $ENV{SHELL} ], undef, 'default', undef);
 
$w->main;
